name: Ping Render Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping-and-keepalive:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing changes
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Uses the default GitHub token

      - name: Create keep-alive file
        run: |
          mkdir -p .github
          date >> .github/keep-alive.txt

      - name: Commit keep-alive changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .github/keep-alive.txt
          git diff-index --quiet HEAD || git commit -m "Keep-alive commit"
          git push

      - name: Ping Render Server
        run: |
          echo "Pinging Render server..."
          response=$(curl -s -o /dev/null -w "%{http_code}" https://taskflow-8d1s.onrender.com/api/ping)
          if [ "$response" -eq 200 ]; then
            echo "Ping successful (Status: $response)"
          else
            echo "Ping failed (Status: $response)"
            exit 1
          fi